### ISSUE TITLE
Nativo

### ISSUE THREAD

**Issue by Luis-Improise** [codhab/guideliness#23]
- [ ] Reduzir tamanho do app
- [x] Desempenho da bateria
- [x] Ícones mesmo padrão Iframe
- [x] Alterar postos de arquitetura para postos de assistência técnica
- [x] Alterar URLs
  - [x] Entidades = mobile.df.gov.br/entities
  - [x] Habitação Pesquisa = /candidate/search
  - [x] Regularização Pesquisa = /candidate/search
  - [x] Agendamentos = /schedule
  - [x] Postos de Assistência Técnica = /tecnhical-assistence
  - [x] Portal = /portal
  - [x] Noticias = /portal/notices
- [x] Retirar Manual de Entidades
- [x] Ajustar cor do login do app com o iframe
- [x] Atualizar botões de voltar
- [x] Loading (nova imagem)
- [x] testar versão Apple
- [x] Ver Crosswalk no IOS
- [x] Alteranativa do crosswalk
- [x] Subir versão beta Android

**Comment by silvaelton** [comment]
Mudar

- [ ] Agendamentos = /candidate/schedule
- [ ] Postos de Assistência Técnica = /portal/tecnhical-assistence
