### ISSUE TITLE
Iframe

### ISSUE THREAD

**Issue by Luis-Improise** [codhab/guideliness#24]
## Mobile

- [x] Alterar "Meus Chats" para "Minhas Conversas"
- [x] Implementar Minhas Conversas @igormarjes 
- [x] Implementar "Meus Requerimentos" @igormarjes 
- [x] Planejar menu Serviços @Luis-Improise
- [x] Notificações - Um ícone por categoria @silvaelton
- [x] Notificações - Incluir o ano após o título @silvaelton
- [x] Botão voltar - Ajustar tamanho de área @silvaelton
- [x] Recadastramento - Papel Bebê @silvaelton
- [x] Atendimento Habilitado @silvaelton
- [x] Alterar foto @silvaelton
- [x] Meu cadastro @igormarjes 
- [x] Meus dependentes @igormarjes 
- [x] Pontuações @igormarjes 
- [x] Ocorrências @igormarjes 
- [x] Minha entidade - Se RIE e se Entidade cadastrada @igormarjes 
- [x] Minhas Situações @igormarjes 
- [x] Endereços vinculados @igormarjes 
- [x] Processos/Documentos @igormarjes 
- [x] Agendamentos @igormarjes 
- [x] Indicação à Empreendimento @igormarjes 
- [x] mandar e-mail junto com push para o e-mail cadastrado @silvaelton
- [x] upload de arquivos real time @silvaelton

# Iframe
- [x] Pesquisa cadastro @silvaelton
- [x] Entidades @silvaelton

 
# Verificações realziadas no APP
- [x] Alterar o label interno de "Atualização Cadastral" para "Atualização de Dados Básicos" @silvaelton
- [x] Na mensagem de retorno no APP, colocar uma borda ou deixar de forma mais clara o comentário do atendente @silvaelton
- [x] No envio de documentações alterar o label de exigência de documentos de deficiência de "Comprovantes de necessidades especiais" para "Comprovantes da deficiência declarada" @silvaelton
- [x] Colocar a obrigatoriedade de upload de arquivo por contexto ou no mínimo dos campos alterados.  Podendo ser mais arquivos mas vazios. O sistema deve acusar essa transação como erro. @silvaelton
- [x] Ao pressionar o link para visualizar a documentação não há como voltar para a página anterior. Criar um botão de voltar. @silvaelton
- [x] Quando não houver documentação a ser enviada mudar o nome do botão de "Enviar Documentação" para "Confirmar alterações" @silvaelton
- [x] Permitir a inclusão de dependentes @silvaelton
- [x]  Quando um dependente for retirado finalizar o atendimento direto, já que não será necessária a validação da CODHAB. @silvaelton
- [x] Colocar um botão de refresh em cadas página para que não seja necessário sair e entrar para atualizar @silvaelton
- [x] Ao atualizar a renda, mesmo atualizado de somente 1, foi apresentado 5 possibilidades de uploads de arquivo. Apresentar somente a quantidade que foi alterada. @silvaelton
- [x] Ao entrar em "Minhas Atualizações" e clicar em voltar o app está voltado para o link errado @silvaelton
- [x] O balão de notificações do APP ainda não está batendo com as notificações internas, pois pelo que observei o balão só mostra a quantidade de notificações com Titulo. @silvaelton
- [x] Melhorar apresentação da Lista de Entidades @silvaelton
- [x] Reformatar os atendimentos, pois estão no Portal @silvaelton
- [x] Padronizar o botão de voltar no Envio de documentos. @silvaelton

## Servidores

- [x] balanceador de carga @silvaelton
- [x] otimização de workers & procs @silvaelton
- [x] otimização de caches @silvaelton

**Comment by Luis-Improise** [comment]
# Verificações realziadas no APP
- [x] Alterar o label interno de "Atualização Cadastral" para "Atualização de Dados Básicos" @silvaelton
- [x] Na mensagem de retorno no APP, colocar uma borda ou deixar de forma mais clara o comentário do atendente @silvaelton
- [x] No envio de documentações alterar o label de exigência de documentos de deficiência de "Comprovantes de necessidades especiais" para "Comprovantes da deficiência declarada" @silvaelton
- [ ] Colocar a obrigatoriedade de upload de arquivo por contexto ou no mínimo dos campos alterados. Podendo ser mais arquivos mas vazios. O sistema deve acusar essa transação como erro. @silvaelton
- [x] Ao pressionar o link para visualizar a documentação não há como voltar para a página anterior. Criar um botão de voltar. @silvaelton
- [ ] Quando não houver documentação a ser enviada mudar o nome do botão de "Enviar Documentação" para "Confirmar alterações" @silvaelton
- [ ] Permitir a inclusão de dependentes @silvaelton
- [ ]  Quando um dependente for retirado finalizar o atendimento direto, já que não será necessária a validação da CODHAB. @silvaelton
- [ ] Colocar um botão de refresh em cadas página para que não seja necessário sair e entrar para atualizar @silvaelton
- [ ] Ao atualizar a renda, mesmo atualizado de somente 1, foi apresentado 5 possibilidades de uploads de arquivo. Apresentar somente a quantidade que foi alterada. @silvaelton
- [ ] Ao entrar em "Minhas Atualizações" e clicar em voltar o app está voltado para o link errado @silvaelton
- [ ] O balão de notificações do APP ainda não está batendo com as notificações internas, pois pelo que observei o balão só mostra a quantidade de notificações com Titulo. @silvaelton
- [ ] Melhorar apresentação da Lista de Entidades @silvaelton
- [ ] Reformatar os atendimentos, pois estão no Portal @silvaelton
- [ ] Padronizar o botão de voltar no Envio de documentos. @silvaelton

**Comment by silvaelton** [comment]
## Servidores

- [ ] balanceador de carga @silvaelton
- [ ] otimização de workers & procs @silvaelton
- [ ] otimização de caches @silvaelton
