### ISSUE TITLE
Entidade no APP

### ISSUE THREAD

**Issue by Luis-Improise** [codhab/guideliness#58]

**Comment by silvaelton** [comment]
@Luis-Improise 

1. Quais os requisitos do formulário.
2. Necessário geolocalização de quem loga na área das entidades?

**Comment by Luis-Improise** [comment]
@silvaelton 
- [ ] Criar formulário dinâmico com no máximo 20 perguntas.
- [ ] As perguntas devem estar no banco, para que possamos parametrizá-las de acordo com a necessidade do negócio.
- [ ] Colocar parâmetro de subida de arquivo sim ou não. Assim quando 15 das 20 perguntas forem selecionadas, podemos dizer facilmente, quais delas podem ou devem subir arquivos.
- [ ] Na pagina principal trazer os dados básicos da entidade (CNPJ, nome, sigla, presidente e situação)
- [ ] O Push e o e-mail devem funcionar
- [ ] A geolocalização seria interessante
- [ ] Colocar requerimento para entidade

Se der tempo
- [ ] Atualização dos dados da entidade
- [ ] Impugnação/desimpugnação de candidato
- [ ] Indicar candidato ao empreendimento
